"""
Django settings for taskmanager project.

This module contains all the configuration settings for the Django project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-here'  # Secret key for cryptographic signing

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Debug mode (set to False in production)

ALLOWED_HOSTS = []  # Hosts/domain names this Django site can serve


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',   # Authentication system
    'django.contrib.contenttypes',  # Content type system
    'django.contrib.sessions',  # Session framework
    'django.contrib.messages',  # Message framework
    'django.contrib.staticfiles',  # Static file handling
    'tasks',  # Our task management app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Security features
    'django.contrib.sessions.middleware.SessionMiddleware',  # Session handling
    'django.middleware.common.CommonMiddleware',  # Common functionality
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Authentication
    'django.contrib.messages.middleware.MessageMiddleware',  # Message handling
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Clickjacking protection
]

ROOT_URLCONF = 'taskmanager.urls'  # Main URL configuration

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Template engine
        'DIRS': [],  # Additional directories for templates
        'APP_DIRS': True,  # Look for templates inside installed apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # Adds debug context
                'django.template.context_processors.request',  # Adds request object to context
                'django.contrib.auth.context_processors.auth',  # Adds user/auth context
                'django.contrib.messages.context_processors.messages',  # Adds messages context
            ],
        },
    },
]

WSGI_APPLICATION = 'taskmanager.wsgi.application'  # WSGI application entry point


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # MySQL backend
        'NAME': 'taskmanager_db',   # <-- your MySQL database name
        'USER': 'root',             # <-- your MySQL username
        'PASSWORD': 'security',         # <-- your MySQL password
        'HOST': 'localhost',        # <-- usually localhost
        'PORT': '3306',             # <-- default MySQL port
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'  # Default language

TIME_ZONE = 'UTC'        # Default timezone

USE_I18N = True          # Enable Django's translation system

USE_TZ = True            # Enable timezone-aware datetimes


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'  # URL to use when referring to static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Additional static files directory
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Directory for collectstatic

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Default PK type for models

LOGIN_URL = 'login'                # Where to redirect for login
LOGIN_REDIRECT_URL = 'dashboard'   # Where to go after login
LOGOUT_REDIRECT_URL = 'home'       # Where to go after logout
